- hosts: all
  become: yes
  roles:
    - { role: bootstrap, tags: ['bootstrap'] }

- hosts: node:master
  become: yes
  roles:
    - { role: docker, tags: ['node', 'master', 'docker'] }
    
- hosts: node
  become: yes
  roles:
    - { role: node, tags: ['node'] }