- hosts: all
  become: yes
  roles:
    - { role: bootstrap, tags: ['bootstrap'] }

- hosts: etcd
  become: yes
  roles:
    - { role: etcd, tags: ['etcd'] }

- hosts: kube-master
  become: yes
  roles:
    - { role: kube-master, tags: ['master'] }