- hosts: all
  become: yes
  roles:
    - { role: bootstrap, tags: ['bootstrap'] }

- hosts: load-balancer
  become: yes
  roles:
    - { role: load-balancer, tags: ['load-balancer'] }

- hosts: node:master
  become: yes
  roles:
    - { role: docker, tags: ['node', 'master', 'docker'] }
    
- hosts: node
  become: yes
  roles:
    - { role: node, tags: ['node'] }