- hosts: all
  become: yes
  roles:
    - { role: bootstrap, tags: ['bootstrap'] }

- hosts: etcd
  become: yes
  roles:
    - { role: etcd, tags: ['etcd'] }

- hosts: master
  become: yes
  roles:
    - { role: master, tags: ['master'] }

- hosts: load-balancer
  become: yes
  roles:
    - { role: load-balancer, tags: ['lb'] }

- hosts: worker
  become: yes
  roles:
    - { role: worker, tags: ['worker'] }