Vagrant.configure("2") do |config|
  config.vm.define "lb01" do |m|
    m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

    m.ssh.username = "vagrant"
    m.ssh.password = "vagrant"
    m.vm.network "private_network", ip: "192.168.50.10"
    m.vm.hostname = "lb01"

    m.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 512
      v.name = "lb01.vagrant.example"
      v.gui = false
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define "master01" do |m|
    m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

    m.ssh.username = "vagrant"
    m.ssh.password = "vagrant"
    m.vm.network "private_network", ip: "192.168.50.11"
    m.vm.hostname = "master01"

    m.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
      v.name = "master01.vagrant.example"
      v.gui = false
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define "master02" do |m|
    m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

    m.ssh.username = "vagrant"
    m.ssh.password = "vagrant"
    m.vm.network "private_network", ip: "192.168.50.12"
    m.vm.hostname = "master02"

    m.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
      v.name = "master02.vagrant.example"
      v.gui = false
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define "master03" do |m|
    m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

    m.ssh.username = "vagrant"
    m.ssh.password = "vagrant"
    m.vm.network "private_network", ip: "192.168.50.13"
    m.vm.hostname = "master03"

    m.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 2048
      v.name = "master03.vagrant.example"
      v.gui = false
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define "worker01" do |w|
    w.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

    w.ssh.username = "vagrant"
    w.ssh.password = "vagrant"
    w.vm.network "private_network", ip: "192.168.50.20"
    w.vm.hostname = "worker01"

    w.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 2048
      v.name = "worker01.vagrant.example"
      v.gui = false
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define "worker02" do |w|
    w.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

    w.ssh.username = "vagrant"
    w.ssh.password = "vagrant"
    w.vm.network "private_network", ip: "192.168.50.21"
    w.vm.hostname = "worker02"

    w.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 2048
      v.name = "worker02.vagrant.example"
      v.gui = false
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
end
