- name: create etcd directory stucture
  file: path=/opt/etcd/{{ item }} state=directory owner=etcd group=etcd
  with_items:
    - ssl
    - data

- name: upload certs
  copy: src=../../../../Certificates/{{ clusterName }}/out/{{ item }} dest=/opt/etcd/ssl owner=etcd group=etcd mode=0600
  with_items:
    - "{{ inventory_hostname }}.{{ clusterDomain }}.csr"
    - "{{ inventory_hostname }}.{{ clusterDomain }}.pem"
    - "{{ inventory_hostname }}.{{ clusterDomain }}-key.pem"
    - ca.pem
    - ca-key.pem

- name: extract etcd
  unarchive: src=/tmp/etcd-{{ etcdVer }}-linux-amd64.tar.gz dest=/opt/etcd/ remote_src=yes

- name: Deploy etcd service unit file
  template: src=etcd.service dest=/etc/systemd/system/etcd.service
  notify: reload etcd

- name: Make etcd executable
  file: path=/opt/etcd/etcd-{{ etcdVer }}-linux-amd64/{{ item }} mode=0755
  with_items:
    - etcd
    - etcdctl

- name: Install etcd service
  service: name=etcd enabled=yes state=started
