- name: cleanup old versions of docker
  apt:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository.
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    name: 'docker-ce={{ dockerVersion }}'
    state: present

- name: enable docker service
  service: name=docker state=started enabled=yes

- name: Add Kuberentes user to the docker group
  user:
    name: kubernetes
    state: present
    append: yes
    groups:
      - docker