- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
  
- name: Remove swapfile from /etc/fstab
  replace:
    dest: "/etc/fstab"
    regexp: '(?i)^(^/dev/mapper/.*swap.*)'
    line: '# \1'
    backrefs: yes
    state: present
  notify: mount all