- name: Remove swapfile from /etc/fstab
  mount:
    name: "/dev/mapper/vagrant--vg-swap_1"
    fstype: swap
    state: absent
    
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0