- name: Ensure group "balancer" exists
  group:
    name: balancer
    state: present

- name: Create "balancer" user
  user:
   name: balancer
   state: present
   groups:
     - balancer
   shell: /bin/nologin
   system: yes
   createhome: no

