 - name: Ensure group "kubernetes" exists
   group:
     name: kubernetes
     state: present

 - name: Create kubernetess user
   user:
    name: kubernetes
    state: present
    groups:
      - kubernetes
    shell: /bin/nologin
    system: yes
    createhome: no