- name: Setup master directory structure
  file:
    path: /opt/kubernetes/{{ item }}
    state: directory
    mode: 0755
    owner: kubernetes
    group: kubernetes
  with_items:
    - kubernetes-{{ kubernetesVer }}-linux-amd64
    - log
    - ssl