- name: Download kubernetes Controller Manager
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/{{ kubernetesVer }}/bin/linux/amd64/{{ item }}
    dest: /opt/kubernetes/kubernetes-{{ kubernetesVer }}-linux-amd64/bin/{{ item }}
    owner: kubernetes
    group: kubernetes
    mode: 0755
  with_items:
    - kube-controller-manager

- name: Deploy Kubernetes Controller Manager kubeconfig
  copy: src=../../../../Konfiguration/{{ clusterName }}/out/kube-controller-manager.kubeconfig dest=/opt/kubernetes/config/ owner=kubernetes group=kubernetes mode=0600

- name: Deploy Kubernetes Controller Manager service script
  template: src=kube-controller-manager.service dest=/etc/systemd/system/kube-controller-manager.service
  notify: reload kube-controller-manager

- name: Install Kubernetes Controller Manager Service
  service: name=kube-controller-manager enabled=yes state=started
