kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/opt/kubernetes/ssl/ca.pem"
authorization:
  mode: Webhook
clusterDomain: "cluster.local"
clusterDNS:
  - "10.32.0.10"
podCIDR: "{{ podCidr }}"
runtimeRequestTimeout: "15m"
tlsCertFile: "/opt/kubernetes/ssl/{{ inventory_hostname }}.{{ clusterDomain }}.pem"
tlsPrivateKeyFile: "/opt/kubernetes/ssl/{{ inventory_hostname }}.{{ clusterDomain }}-key.pem"