- name: Download kube-router tarball
  get_url:
    url: https://github.com/cloudnativelabs/kube-router/releases/download/v{{ kubeRouterVer }}/kube-router_{{ kubeRouterVer }}_linux_amd64.tar.gz
    dest: /opt/archives/kube-router_{{ kubeRouterVer }}_linux_amd64.tar.gz
    owner: kubernetes
    group: kubernetes
    mode: 0755

- name: extract kube-router
  unarchive:
    src: /opt/archives/kube-router_{{ kubeRouterVer }}_linux_amd64.tar.gz
    dest: /opt/kubernetes/kube-router-{{ kubeRouterVer }}/bin
    owner: kubernetes
    group: kubernetes
    remote_src: yes

- name: make kube-router executable
  file:
    path: /opt/kubernetes/kube-router-{{ kubeRouterVer }}/bin/kube-router
    mode: 0700
    owner: kubernetes
    group: kubernetes

- name: Upload kubelet kubeconfig
  copy:
    src: ../../../../Konfiguration/vagrant/kube-router.kubeconfig
    dest: /opt/kubernetes/config/kube-router.kubeconfig
    owner: kubernetes
    group: kubernetes
    mode: 0600

- name: upload kube-router service script
  template:
    src: kube-router.service
    dest: /etc/systemd/system/kube-router.service
