Vagrant.configure("2") do |config|
  config.vm.define "lb01" do |m|
      m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

      m.ssh.username = "vagrant"
      m.ssh.password = "vagrant"
      m.vm.network "private_network", ip: "192.168.50.10"
      m.vm.hostname = "lb01"

      m.vm.provider "virtualbox" do |v|
        v.cpus = 1
        v.memory = 512
        v.name = "lb01.vagrant.example"
        v.gui = false
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
      end
    end

  config.vm.define "master01" do |m|
    m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

    m.ssh.username = "vagrant"
    m.ssh.password = "vagrant"
    m.vm.network "private_network", ip: "192.168.50.11"
    m.vm.hostname = "master01"

    m.vm.provider "virtualbox" do |v|
      v.cpus = 1
      v.memory = 1024
      v.name = "master01.vagrant.example"
      v.gui = false
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  config.vm.define "master02" do |m|
      m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

      m.ssh.username = "vagrant"
      m.ssh.password = "vagrant"
      m.vm.network "private_network", ip: "192.168.50.12"
      m.vm.hostname = "master02"

      m.vm.provider "virtualbox" do |v|
        v.cpus = 1
        v.memory = 1024
        v.name = "master02.vagrant.example"
        v.gui = false
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
      end
  end

  config.vm.define "master03" do |m|
      m.vm.box = "file://../VMBuild/builds/virtualbox-ubuntu1604.box"

      m.ssh.username = "vagrant"
      m.ssh.password = "vagrant"
      m.vm.network "private_network", ip: "192.168.50.13"
      m.vm.hostname = "master03"

      m.vm.provider "virtualbox" do |v|
        v.cpus = 1
        v.memory = 1024
        v.name = "master03.vagrant.example"
        v.gui = false
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--ioapic", "on"]
      end
  end

end
